blueprint:
  description: An active blueprint description
  active: true

  deploy:
    source:
      machine: local
      folder: /path/to/folder/

    destinations:
      - destination:
        machine: local
        folder: /path/to/deployed/folder/
