blueprint:
  description: Copy local->remote
  active: true
  logging: auto

  deploy:
    source:
      machine: local
      type: folder
      folder: /path/to/local/source/
      filter:
        - .git # Ignores the .git folder and its contents

    destinations:
      - machine: remote1
        folder: /path/to/remote/folder/
