blueprint:
  description: An active blueprint description
  active: false

  deploy:
    source:
      machine: local
      runas: root
      folder: /path/to/folder/

    destinations:
      - machine: local
        runas: root
        folder: /path/to/deployed/folder/
