blueprint:
  description: Copy local->remote
  active: true
  logging: auto

  deploy:
    source:
      machine: local
      run-as: root
      type: folder
      folder: /path/to/local/source/
      filter:
        - .git

    destinations:
      - machine: remote1
        run-as: root
        folder: /path/to/remote/folder/
